apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ffc-demo-base
  namespace: config-cluster-flux
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: config-cluster-flux
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/ffc-demo/${ENVIRONMENT}/${CLUSTER}
  postBuild:
    substitute:
      NAMESPACE: "ffc-demo"
      WORKLOAD_IDENTITY_ID: "3acd7d69-86fb-40ce-a389-4632e864e425"
      TEAM_NAME: "ffc-demo-team"
      ENVIRONMENT: "${ENVIRONMENT}"
      ACR_NAME: "${ACR_NAME}"
      CLUSTER: "\"${CLUSTER}\""
      CLUSTER_OIDC: "https://uksouth.oic.prod-aks.azure.com/6f504113-6b64-43f2-ade9-242e05780007/47f13011-3d77-4264-9029-6bf061a21092/"
      TENANT_ID: "6f504113-6b64-43f2-ade9-242e05780007"
      #TENANT_ID: "NmY1MDQxMTMtNmI2NC00M2YyLWFkZTktMjQyZTA1NzgwMDA3"
      SUBSCRIPTION_ID: "55f3b8c6-6800-41c7-a40d-2adb5e4e1bd1"
      #SUBSCRIPTION_ID: "NTVmM2I4YzYtNjgwMC00MWM3LWE0MGQtMmFkYjVlNGUxYmQx"
      #SUBSCRIPTION_ID_STRING: "55f3b8c6-6800-41c7-a40d-2adb5e4e1bd1"
      CLIENT_ID: "411ae1f5-10d7-4cb9-8de6-85145e64c7d5"
      SERVICEBUS_RG: "${SERVICEBUS_RG}"
      SERVICEBUS_NS: "${SERVICEBUS_NS}"
      INFRA_RG: "${INFRA_RG}"
      TEAM_MI_NAME: "${TEAM_MI_NAME}"