apiVersion: v1
data:
  AZURE_CLIENT_ID: NGJjMTVjY2ItZWY4OS00ZTM2LWFmOTgtZWQwNmI3ODMwYzFi
  AZURE_SUBSCRIPTION_ID: NTVmM2I4YzYtNjgwMC00MWM3LWE0MGQtMmFkYjVlNGUxYmQx
  AZURE_TENANT_ID: NmY1MDQxMTMtNmI2NC00M2YyLWFkZTktMjQyZTA1NzgwMDA3
  USE_WORKLOAD_IDENTITY_AUTH: dHJ1ZQ==
kind: Secret
metadata:
  name: aso-credential
  namespace: team-gg
type: Opaque