apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: aso-mi-rg
  namespace: platform-team
spec:
  location: uksouth
# Resource group containing managed identities which is managed by the Platform Team