apiVersion: managedidentity.azure.com/v1api20181130
kind: UserAssignedIdentity
metadata:
  name: ${NAMESPACE}-aso-mi
  namespace: platform-team
spec:
  location: uksouth
  owner:
    name: aso-mi-rg # THIS NEEDS TO BE A MANAGED IDENTITY RESOURCE GROUP MANAGED BY THE PLATFORM TEAM
  operatorSpec:
    configMaps:
      principalId:
        name: ${NAMESPACE}-aso-mi-identity-settings
        key: principalId
      clientId:
        name: ${NAMESPACE}-aso-mi-identity-settings
        key: clientId