apiVersion: servicebus.azure.com/v1api20210101preview
kind: Namespace
metadata:
  name: asoservicebus
  #namespace: platform-team
  namespace: team-aa
  #annotations:
  #  serviceoperator.azure.com/reconcile-policy: skip
spec:
  location: uksouth
  owner:
    name: aso-mi-rg-delete
  sku:
    name: Basic
  zoneRedundant: false