apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adp-demo-base
  namespace: config-cluster-flux
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: config-cluster-flux
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/adp-demo/${ENVIRONMENT}/${CLUSTER}
  postBuild:
    substitute:
      NAMESPACE: "adp-demo"
      WORKLOAD_IDENTITY_ID: "3acd7d69-86fb-40ce-a389-4632e864e425"
      TEAM_NAME: "adp-demo-team"
      CLIENT_ID: "" # TEAM MI CLIENT_ID
      TEAM_RG: "sndadpinfrg1401"
      ENVIRONMENT: "${ENVIRONMENT}"
      ACR_NAME: "${ACR_NAME}"
      CLUSTER: "\"${CLUSTER}\""
      CLUSTER_OIDC: "${CLUSTER_OIDC}"
      TENANT_ID: "${TENANT_ID}" 
      SUBSCRIPTION_ID: "${SUBSCRIPTION_ID}"
      SUBSCRIPTION_NAME: "${SUBSCRIPTION_NAME}"
      SERVICEBUS_RG: "${SERVICEBUS_RG}"
      SERVICEBUS_NS: "${SERVICEBUS_NS}"
      INFRA_RG: "${INFRA_RG}"
      TEAM_MI_NAME: "${TEAM_MI_NAME}"
      POSTGRES_SERVER_RG: "${POSTGRES_SERVER_RG}"
      POSTGRES_SERVER: "${POSTGRES_SERVER}"