apiVersion: v1
kind: Secret
metadata:
  name: aso-credential
  namespace: ${NAMESPACE}
stringData:
  AZURE_CLIENT_ID: "bf9f06e3-b08f-40f9-82d2-6d216963b098"
  AZURE_SUBSCRIPTION_ID: ${SUBSCRIPTION_ID}
  AZURE_TENANT_ID: ${TENANT_ID}
  USE_WORKLOAD_IDENTITY_AUTH: "true"