apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  name: ${NAMESPACE}-aso-fic
  namespace: platform-team
spec:
  owner:
    name: ${NAMESPACE}-aso-mi
  audiences:
    - api://AzureADTokenExchange
  # For Workload Identity, Issuer should be the OIDC endpoint of the cluster. For AKS this will look like
  # https://oidc.prod-aks.azure.com/00000000-0000-0000-0000-00000000000/
  issuer: ${CLUSTER_OIDC}
  # For Workload Identity, Subject should always be system:serviceaccount:<namespace>:<serviceaccount>
  subject: system:serviceaccount:azureserviceoperator-system:azureserviceoperator-default