apiVersion: managedidentity.azure.com/v1api20220131preview
kind: FederatedIdentityCredential
metadata:
  name: ${TEAM_MI_NAME}-${NAMESPACE}-ab-fic
  namespace: config-cluster-flux
spec:
  owner:
    name: ${TEAM_MI_NAME}-${NAMESPACE}-ab
  audiences:
    - api://AzureADTokenExchange
  issuer: ${CLUSTER_OIDC}
  subject: system:serviceaccount:azureserviceoperator-system:azureserviceoperator-default