apiVersion: authorization.azure.com/v1api20200801preview
kind: RoleAssignment
metadata:
  name: ${SUBSCRIPTION_NAME}-${POSTGRES_SERVER_RG}-${POSTGRES_SERVER}-${NAMESPACE}-aso-pgdb-rbac
  namespace: platform-team
spec:
  owner:
    armId: /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${POSTGRES_SERVER_RG}/providers/Microsoft.DBforPostgreSQL/flexibleServers/${POSTGRES_SERVER}
  principalIdFromConfig:
    name: ${NAMESPACE}-aso-mi-identity-settings
    key: principalId
  roleDefinitionReference:
    # This ARM ID represents "Contributor" - you can read about other built in roles here: https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles
    armId: /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c
    # Needs to be a custom role with lesser privileges