apiVersion: dbforpostgresql.azure.com/v1api20220120preview
kind: FlexibleServersDatabase
metadata:
  name: ${NAMESPACE}-asotestdb
  namespace: ${NAMESPACE}
spec:
  owner:
    armId: /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${POSTGRES_SERVER_RG}/providers/Microsoft.DBforPostgreSQL/flexibleServers/${POSTGRES_SERVER}
  charset: utf8