apiVersion: servicebus.azure.com/v1api20210101preview
kind: NamespacesQueue
metadata:
  name: ffc-demo-helm4
  namespace: ${NAMESPACE}
  annotations:
    serviceoperator.azure.com/reconcile-policy: skip
spec:
  maxDeliveryCount: 20
  owner:
    armId: /subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${SERVICEBUS_RG}/providers/Microsoft.ServiceBus/namespaces/${SERVICEBUS_NS}