apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - aso-helm-repository.yaml
  # - aso-helm-release.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - image-repository.yaml  
  - image-policy.yaml
  - demo-sb-queue.yaml # Need to be moved out and included in ASO abstraction work
  - demo-db-postgres.yaml # Need to be moved out and included in ASO abstraction work
  #- demo-sb-queue.yaml # Need to be moved out and included in ASO abstraction work
  #- demo-db-postgres.yaml # Need to be moved out and included in ASO abstraction work
