apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-cluster-flux
  namespace: config-cluster-flux
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: config-cluster-flux
  interval: 5m
  timeout: 3m
  prune: true
  path: ./services/environments/snd/01
  postBuild:
    substitute:
      NAMESPACE: "ffc-demo"
      ENVIRONMENT: "snd"
      ACR_NAME: "sndcdoinfcr2401p"
      CLUSTER: "00"
      WORKLOAD_IDENTITY_ID: "3acd7d69-86fb-40ce-a389-4632e864e425"
      TEAM_NAME: "ffc-demo-team"

