apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-base
resources:
  - ../../base
  - repository.yaml
  - release.yaml

patches:
  - path: snd.yaml
#  - kustomize.yaml
#  - ../base
  